language: julia
os:
  - linux
julia:
  - release
  - nightly
sudo: false
script:
  - julia --check-bounds=yes -e 'Pkg.add("Iterators"); Pkg.clone(pwd()); Pkg.build("Sudoku"); Pkg.test("Sudoku"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("LightGraphs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
